AddTextEntry("bat1", "Bolted Bat") 
AddTextEntry("ham1", "Sasquatch Hammer")
AddTextEntry("mag1", "Police Nightstick")
AddTextEntry("mag2", "Police Nightstick V.2")
AddTextEntry("ascia", "Advanced Hatchet")
AddTextEntry("col1", "Hunter's Knife")
AddTextEntry("colcuoco", "Chef's Knife")
AddTextEntry("machetemael", "Maelstrom Machete")
AddTextEntry("machetecustom", "Machete Custom")
AddTextEntry("motosega", "Cut-o-Matic")
AddTextEntry("tsunami", "Tsunami Kappa")
AddTextEntry("carnage", "Budget Arms Carnage")
AddTextEntry("umbra", "Darra Polytechnic DA8 Umbra")